### ISSUE TITLE
Testing with pybullet

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/motion_planning_scenes#12]
There should be a way to test individual obstacles/goal with pybullet and the rendering.

**Comment by maxspahn** [comment]
It might be possible now as gym_envs_urdf are public.

**Comment by maxspahn** [comment]
Made use of pure pybullet in #35

**Comment by GijsGroote** [comment]
currently, when running all test with:
`
pytest tests/
`
An error is raised because pybullet is not installed on default. 
pybullet is imported by tests:

ERROR tests/pybullet/test_pybullet_goals.py
ERROR tests/pybullet/test_pybullet_obstacles.py

proposed solution: import pybullet on default.

**Comment by maxspahn** [comment]
The option '-E pybullet' in .github/workflows/unitTest.yml should install pybullet for testing, thus making it available for unittesting
